server:
  port: 9777

spring:
  datasource:
    url: jdbc:h2:file:/data/database/ABNrecipes
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console.enabled: true

logging:
  level:
    eu.paulharris: info
